CREATE TABLE Suppliers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(150) NOT NULL,
  country VARCHAR(50) NOT NULL
);

CREATE TABLE Categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE Products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,

  supplier_id INT,
  CONSTRAINT fk_supplier
      FOREIGN KEY(supplier_id) 
          REFERENCES Suppliers(id)
              ON DELETE CASCADE,

  category_id INT,
  CONSTRAINT fk_category
      FOREIGN KEY(category_id) 
          REFERENCES Categories(id)
              ON DELETE CASCADE
);
